const translations={
es:{eyebrow:'COCINA CASERA · SABOR SIN FRONTERAS',heroTitle:'Tu mesa, llena de<br><em>buenos momentos.</em>',heroIntro:'Tapas de siempre, bocadillos generosos y especialidades asiáticas hechas al momento.',viewMenu:'Ver la carta',ourMenu:'NUESTRA CARTA',choose:'¿Qué te apetece hoy?',search:'Buscar un plato…',all:'Todo',noResults:'No hemos encontrado ningún plato.',allergyTitle:'¿Tienes alguna alergia?',allergyText:'Habla con nuestro equipo antes de pedir. Estaremos encantados de ayudarte.',footer:'Hecho con cariño · Precios con IVA incluido',backTop:'Volver arriba ↑',withSide:'Con ensalada o huevo frito y patatas',extra:'Con patatas y refresco: suplemento de 2,90 €'},
ca:{eyebrow:'CUINA CASOLANA · SABOR SENSE FRONTERES',heroTitle:'La teva taula, plena de<br><em>bons moments.</em>',heroIntro:'Tapes de sempre, entrepans generosos i especialitats asiàtiques fetes al moment.',viewMenu:'Veure la carta',ourMenu:'LA NOSTRA CARTA',choose:'Què et ve de gust avui?',search:'Cercar un plat…',all:'Tot',noResults:'No hem trobat cap plat.',allergyTitle:'Tens alguna al·lèrgia?',allergyText:'Parla amb el nostre equip abans de demanar. Estarem encantats d’ajudar-te.',footer:'Fet amb afecte · Preus amb IVA inclòs',backTop:'Tornar a dalt ↑',withSide:'Amb amanida o ou ferrat i patates',extra:'Amb patates i refresc: suplement de 2,90 €'},
en:{eyebrow:'HOME COOKING · FLAVOUR WITHOUT BORDERS',heroTitle:'Your table, full of<br><em>good moments.</em>',heroIntro:'Classic tapas, generous sandwiches and Asian specialities freshly made to order.',viewMenu:'View menu',ourMenu:'OUR MENU',choose:'What are you craving?',search:'Search dishes…',all:'All',noResults:'No dishes found.',allergyTitle:'Do you have an allergy?',allergyText:'Please speak to our team before ordering. We’ll be happy to help.',footer:'Made with love · VAT included',backTop:'Back to top ↑',withSide:'With salad or fried egg and chips',extra:'Add chips and a soft drink for €2.90'},
zh:{eyebrow:'家常料理 · 跨越國界的美味',heroTitle:'一桌美食，盛滿<br><em>美好時光。</em>',heroIntro:'經典西班牙小食、份量十足的三明治，以及現點現做的亞洲料理。',viewMenu:'查看菜單',ourMenu:'我們的菜單',choose:'今天想吃什麼？',search:'搜尋菜色…',all:'全部',noResults:'找不到符合的菜色。',allergyTitle:'有食物過敏嗎？',allergyText:'點餐前請告知服務人員，我們很樂意為您提供協助。',footer:'用心製作 · 價格含增值稅',backTop:'回到頂部 ↑',withSide:'附沙拉，或太陽蛋與薯條',extra:'加薯條與汽水另加 2.90 €'}
};
const cats={bocadillos:{icon:'🥖',names:{es:'Bocadillos',ca:'Entrepans',en:'Baguettes',zh:'西班牙長棍三明治'}},hamburguesas:{icon:'🍔',names:{es:'Hamburguesas',ca:'Hamburgueses',en:'Burgers',zh:'漢堡'}},sandwiches:{icon:'🥪',names:{es:'Sándwiches',ca:'Sandvitxos',en:'Sandwiches',zh:'吐司三明治'}},asia:{icon:'🥟',names:{es:'Platos de Asia',ca:'Plats d’Àsia',en:'Asian dishes',zh:'亞洲料理'}},combinados:{icon:'🍽️',names:{es:'Platos combinados',ca:'Plats combinats',en:'Combo plates',zh:'綜合套餐'}},ensaladas:{icon:'🥗',names:{es:'Ensaladas',ca:'Amanides',en:'Salads',zh:'沙拉'}},tapas:{icon:'🫒',names:{es:'Tapas',ca:'Tapes',en:'Tapas',zh:'西班牙小食'}}};
const n=(es,ca,en,zh)=>({es,ca,en,zh});
const menu={
bocadillos:[['Jamón','Pernil','Cured ham','火腿','4,95 €'],['Lomo','Llom','Pork loin','豬里肌','4,95 €'],['Bacon','Bacó','Bacon','培根','5,00 €'],['Fuet','Fuet','Catalan sausage','加泰隆尼亞香腸','5,00 €'],['Pechuga de pollo','Pit de pollastre','Chicken breast','雞胸肉','5,00 €'],['Francesa','Truita francesa','French omelette','歐姆蛋','4,95 €'],['Pincho de cerdo','Broqueta de porc','Pork skewer','豬肉串','6,00 €'],['Serranito','Serranito','Serranito','塞拉諾火腿豬排','6,00 €']],
hamburguesas:[['Hamburguesa de pollo A','Hamburguesa de pollastre A','Chicken burger A','A款雞肉漢堡','7,95 €','Pollo empanado, lechuga, tomate, bacon y queso|Pollastre arrebossat, enciam, tomàquet, bacó i formatge|Breaded chicken, lettuce, tomato, bacon and cheese|炸雞、萵苣、番茄、培根與起司'],['Hamburguesa ternera B','Hamburguesa de vedella B','Beef burger B','B款牛肉漢堡','8,95 €','Carne, lechuga, tomate, cheddar, bacon y huevo|Vedella, enciam, tomàquet, cheddar, bacó i ou|Beef, lettuce, tomato, cheddar, bacon and egg|牛肉、萵苣、番茄、切達起司、培根與蛋']],
sandwiches:[['Mixto','Mixt','Ham & cheese','火腿起司','3,50 €','Jamón york y queso|Pernil dolç i formatge|Cooked ham and cheese|熟火腿與起司'],['Vegetal','Vegetal','Vegetable & tuna','鮪魚蔬菜','4,95 €','Lechuga, tomate, atún, huevo y mayonesa|Enciam, tomàquet, tonyina, ou i maionesa|Lettuce, tomato, tuna, egg and mayonnaise|萵苣、番茄、鮪魚、蛋與美乃滋'],['Inglés','Anglès','English','英式','5,00 €','Jamón york, queso, bacon y huevo frito|Pernil dolç, formatge, bacó i ou ferrat|Cooked ham, cheese, bacon and fried egg|熟火腿、起司、培根與煎蛋']],
asia:[['Sopa de wonton · 6/12 u.','Sopa de wonton · 6/12 u.','Wonton soup · 6/12 pcs','餛飩湯 · 6/12顆','4,95 / 9,90 €'],['Ramen de ternera','Ramen de vedella','Beef ramen','牛肉拉麵','9,95 €'],['Gyoza de gamba · 6/12 u.','Gyoza de gamba · 6/12 u.','Prawn gyoza · 6/12 pcs','鮮蝦煎餃 · 6/12顆','6,95 / 12,00 €'],['Gyoza de ternera · 6/12 u.','Gyoza de vedella · 6/12 u.','Beef gyoza · 6/12 pcs','牛肉煎餃 · 6/12顆','6,95 / 12,00 €'],['Gyoza de cerdo · 6/12 u.','Gyoza de porc · 6/12 u.','Pork gyoza · 6/12 pcs','豬肉煎餃 · 6/12顆','5,95 / 10,00 €'],['Fideos fritos con ternera','Fideus fregits amb vedella','Fried noodles with beef','牛肉炒麵','7,95 €'],['Fideos fritos con gamba','Fideus fregits amb gamba','Fried noodles with prawns','鮮蝦炒麵','7,95 €'],['Arroz frito con pollo','Arròs fregit amb pollastre','Chicken fried rice','雞肉炒飯','6,95 €'],['Arroz frito con ternera o gamba','Arròs fregit amb vedella o gamba','Beef or prawn fried rice','牛肉或鮮蝦炒飯','7,95 €'],['Ternera o pollo salteado con verduras y setas','Vedella o pollastre saltat amb verdures i bolets','Stir-fried beef or chicken with vegetables','時蔬炒牛肉或雞肉','8,95 €'],['Gambas salteadas con verduras','Gambes saltades amb verdures','Stir-fried prawns with vegetables','時蔬炒蝦','8,95 €']],
combinados:[['Filete de pollo','Filet de pollastre','Chicken fillet','雞排','9,95 €'],['Alitas o costilla frita','Aletes o costella fregida','Fried wings or ribs','炸雞翅或排骨','9,95 €'],['Filete de pescado frito','Filet de peix fregit','Fried fish fillet','炸魚排','9,95 €'],['Milanesa de ternera','Milanesa de vedella','Beef milanese','米蘭式炸牛排','9,95 €'],['Churrasco de ternera','Xurrasco de vedella','Grilled beef churrasco','炭烤牛肉','14,95 €'],['Cinta de lomo o chuletas','Cinta de llom o costelles','Pork loin or chops','豬里肌或豬排','9,95 €']],
ensaladas:[['Ensalada A','Amanida A','Salad A','A款沙拉','7,95 €','Lechuga iceberg, tomate, cebolla, queso fresco, atún y salsa de sésamo|Enciam iceberg, tomàquet, ceba, formatge fresc, tonyina i salsa de sèsam|Iceberg lettuce, tomato, onion, fresh cheese, tuna and sesame dressing|冰山萵苣、番茄、洋蔥、鮮起司、鮪魚與芝麻醬'],['Ensalada B','Amanida B','Salad B','B款沙拉','8,95 €','Lechugas, nueces, queso fresco, frutos secos y crema de vinagre|Enciams, nous, formatge fresc, fruits secs i crema de vinagre|Mixed leaves, walnuts, fresh cheese, nuts and balsamic glaze|綜合生菜、核桃、鮮起司、堅果與油醋醬']],
tapas:[['Morros','Morro','Pork snout','炸豬鼻','7,50 €'],['Alitas','Aletes','Chicken wings','雞翅','6,50 €'],['Tapas mix · nuggets, alitas y patatas','Tapes mix · nuggets, aletes i patates','Tapas mix · nuggets, wings & chips','綜合小食 · 雞塊、雞翅與薯條','8,50 €'],['Rejos','Rejos','Fried squid tentacles','炸魷魚鬚','7,95 €'],['Pinchos de cerdo','Broquetes de porc','Pork skewers','豬肉串','7,50 €'],['Calamares','Calamars','Calamari','炸魷魚','7,95 €'],['Gamba frita japonesa','Gamba fregida japonesa','Japanese fried prawns','日式炸蝦','7,95 €'],['Rollitos fritos japoneses','Rotllets fregits japonesos','Japanese fried rolls','日式炸春捲','4,95 €'],['Wonton frito Hong Kong','Wonton fregit Hong Kong','Hong Kong fried wonton','港式炸餛飩','7,95 €'],['Patatas fritas','Patates fregides','Chips','薯條','4,50 €'],['Patatas bravas','Patates braves','Patatas bravas','辣味薯塊','5,50 €']]};
let lang='es',active='all';
const tr=k=>translations[lang][k];
const localText=s=>lang==='zhs'&&s?[...s].map(c=>({'體':'体','國':'国','單':'单','點':'点','現':'现','滿':'满','時':'时','鮮':'鲜','蝦':'虾','雞':'鸡','豬':'猪','魚':'鱼','麵':'面','飯':'饭','餃':'饺','湯':'汤','塊':'块','條':'条','顆':'颗','萵':'莴','與':'与','醬':'酱','頭':'头','鬚':'须','搜尋':'搜索','漢':'汉','歐':'欧','選':'选','擇':'择','價':'价','樂':'乐','為':'为','這':'这','檸':'柠','蘭':'兰','鮪':'鲔','龍':'龙','魷':'鱿','絲':'丝','葉':'叶','燴':'烩','鹽':'盐','乾':'干','後':'后','裡':'里'}[c]||c)).join(''):s;
function renderCategories(){const el=document.querySelector('#categories');el.innerHTML=`<button class="category-btn ${active==='all'?'active':''}" data-cat="all">✦ ${tr('all')}</button>`+Object.entries(cats).map(([k,c])=>`<button class="category-btn ${active===k?'active':''}" data-cat="${k}">${c.icon} ${localText(lang==='zhs'?c.names.zh:(c.names[lang]||c.names.es))}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.cat;renderCategories();renderMenu()})}
function renderMenu(){const q=document.querySelector('#search').value.trim().toLocaleLowerCase();let count=0;const found=['es','ca','en','zh'].indexOf(lang),idx=lang==='zhs'?3:(found<0?0:found);const html=Object.entries(menu).filter(([k])=>active==='all'||active===k).map(([k,items])=>{const filtered=items.filter(i=>i.slice(0,4).some(x=>x.toLocaleLowerCase().includes(q)));if(!filtered.length)return'';count+=filtered.length;return `<article class="menu-card"><div class="card-category"><span>${cats[k].icon}</span>${localText(lang==='zhs'?cats[k].names.zh:(cats[k].names[lang]||cats[k].names.es))}</div>${filtered.map(i=>{const desc=localText(i[5]?.split('|')[idx]);return `<div class="item"><span class="item-name">${localText(i[idx])}</span><span class="price">${i[4]}</span>${desc?`<p class="desc">${desc}</p>`:''}</div>`}).join('')}${k==='combinados'?`<p class="note">＋ ${tr('withSide')}</p>`:''}</article>`}).join('');document.querySelector('#menu').innerHTML=html;document.querySelector('#empty').hidden=count>0}
function applyLang(newLang){lang=newLang;document.documentElement.lang=lang==='zh'?'zh-Hant':lang;document.querySelectorAll('[data-i18n]').forEach(el=>el.innerHTML=tr(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=tr(el.dataset.i18nPlaceholder));document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));renderCategories();renderMenu();localStorage.setItem('sweet-lang',lang)}
document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>applyLang(b.dataset.lang));document.querySelector('#search').addEventListener('input',renderMenu);applyLang(translations[localStorage.getItem('sweet-lang')]?localStorage.getItem('sweet-lang'):'es');
